---
engines:
  duplication:
    config:
      languages:
        - javascript
        - typescript
    minTokenMatch: 40
    ignoreLiterals: true
    ignoreIdentifiers: false
    ignoreAnnotations: true
    skipLexicalErrors: true

engines:
  eslint:
    enabled: true
    config:
      configFile: .eslintrc.cjs
  jshint:
    enabled: false

languages:
  javascript:
    extensions:
      - ".js"
      - ".cjs"
      - ".mjs"
      - ".jsx"
      - ".svelte"
  typescript:
    extensions:
      - ".ts"
      - ".tsx"

exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - "release/**"
  - "coverage/**"
  - "playwright-report/**"
  - "test-results/**"
