// Copyright 2026 Matthew Allen. Licensed under the Modified Apache License, Version 2.0.
import { describe, it, expect, beforeEach } from "vitest";
import {
  checkRemove,
  checkWrite,
  packageForJavaFile,
  suggestedJavaFolder,
} from "../../utils/github/rules";
import { GitHubRepos } from "../../utils/github/repos";
import { memoryRepoStorage } from "../../utils/github/storage";
import { githubPath } from "../../utils/github/paths";
import { FakeGitHub } from "./fakeGitHub";

const JAVA = "TeamCode/src/main/java/org/firstinspires/ftc/teamcode";
const GENERATED = "/* Turtle Tracer — Auto-Generated */\nclass Far {}";

describe("what Turtle Tracer may write in a repository", () => {
  it("writes path projects anywhere", () => {
    expect(() => checkWrite("anywhere/Far.turt", "old")).not.toThrow();
    expect(() => checkWrite("Old.pp", undefined)).not.toThrow();
  });

  it("writes new generated code, and replaces code it generated", () => {
    expect(() => checkWrite(`${JAVA}/Far.java`, undefined)).not.toThrow();
    expect(() => checkWrite(`${JAVA}/Far.java`, GENERATED)).not.toThrow();
    expect(() =>
      checkWrite(
        "paths/Far.json",
        '{"header":{"info":"Created with Turtle Tracer"}}',
      ),
    ).not.toThrow();
    expect(() =>
      checkWrite("paths/Far.txt", "[(9.0, 25.0), (60.000, 25.5)]"),
    ).not.toThrow();
  });

  it("never replaces a file a person wrote", () => {
    expect(() => checkWrite(`${JAVA}/Far.java`, "class Far {}")).toThrow(
      /wasn't generated by Turtle Tracer/,
    );
    expect(() => checkWrite("config.json", '{"motors": 4}')).toThrow(
      /wasn't generated/,
    );
    expect(() => checkWrite("notes.txt", "remember the battery")).toThrow(
      /wasn't generated/,
    );
  });

  it("won't touch anything else", () => {
    for (const path of ["README.md", "build.gradle", "TeamCode/Robot.kt"]) {
      expect(() => checkWrite(path, undefined), path).toThrow(
        /only changes path projects/,
      );
    }
  });

  it("only puts Java where it gets compiled", () => {
    expect(() =>
      checkWrite(
        "TeamCode/src/main/assets/AutoPaths/GeneratedCode/Far.java",
        undefined,
      ),
    ).toThrow(/isn't compiled/);
  });

  it("only deletes or renames path projects", () => {
    expect(() => checkRemove("a/Far.turt")).not.toThrow();
    expect(() => checkRemove(`${JAVA}/Far.java`)).toThrow(/only deletes/);
  });

  it("suggests the package folder in the project's module for generated code", () => {
    const project = "TeamCode/src/main/assets/AutoPaths/Far.turt";
    expect(
      suggestedJavaFolder(project, "org.firstinspires.ftc.teamcode.autos"),
    ).toBe("TeamCode/src/main/java/org/firstinspires/ftc/teamcode/autos");
    expect(
      suggestedJavaFolder("Robot/src/main/assets/AutoPaths/Far.turt", "a.b"),
    ).toBe("Robot/src/main/java/a/b");
    // Outside a module, or with a package Java can't use.
    expect(suggestedJavaFolder("paths/Far.turt", "my package!")).toBe(
      "TeamCode/src/main/java/org/firstinspires/ftc/teamcode",
    );
    expect(suggestedJavaFolder("src/main/assets/Far.turt", "a.b")).toBe(
      "src/main/java/a/b",
    );
  });

  it("works out a Java file's package from its folder", () => {
    expect(packageForJavaFile(`${JAVA}/autos/Far.java`)).toBe(
      "org.firstinspires.ftc.teamcode.autos",
    );
    expect(packageForJavaFile("TeamCode/src/main/java/Far.java")).toBeNull();
    expect(packageForJavaFile("elsewhere/Far.java")).toBeNull();
  });
});

describe("the working copy follows the rules", () => {
  const ref = { owner: "team", repo: "robot" };
  const at = (p: string) => githubPath(ref, p);
  let repos: GitHubRepos;

  beforeEach(async () => {
    const github = new FakeGitHub();
    github.addRepo("team", "robot", {
      "README.md": "# Robot",
      [`${JAVA}/Far.java`]: "class Far { /* written by hand */ }",
      [`${JAVA}/Near.java`]: GENERATED,
    });
    repos = new GitHubRepos(github, memoryRepoStorage());
    await repos.open(ref, "main");
  });

  it("refuses to change other files, and records nothing", async () => {
    await expect(repos.writeFile(at("README.md"), "x")).rejects.toThrow(
      /only changes path projects/,
    );
    await expect(
      repos.writeFile(at(`${JAVA}/Far.java`), GENERATED),
    ).rejects.toThrow(/wasn't generated/);
    await expect(repos.deleteFile(at(`${JAVA}/Near.java`))).rejects.toThrow(
      /only deletes/,
    );
    expect(await repos.changes(ref)).toEqual([]);
  });

  it("regenerates code it generated before", async () => {
    await repos.writeFile(at(`${JAVA}/Near.java`), GENERATED + "\n// v2");
    expect((await repos.changes(ref))[0]).toMatchObject({
      repoPath: `${JAVA}/Near.java`,
      status: "modified",
    });
  });
});
