// Copyright 2026 Matthew Allen. Licensed under the Apache License, Version 2.0.
import type { KeyBinding } from "../types";

/**
 * Default settings
 */
export const DEFAULT_KEY_BINDINGS: KeyBinding[] = [
  // File
  {
    id: "save-project",
    key: "cmd+s, ctrl+s",
    description: "Save project",
    action: "saveProject",
    category: "File",
  },
  {
    id: "save-file-as",
    key: "cmd+shift+s, ctrl+shift+s",
    description: "Save As (download trajectory)",
    action: "saveFileAs",
    category: "File",
  },
  {
    id: "export-gif",
    key: "cmd+shift+e, ctrl+shift+e",
    description: "Export Animated Image",
    action: "exportGif",
    category: "File",
  },

  // Editing
  {
    id: "add-path",
    key: "p",
    description: "Add new path",
    action: "addNewLine",
    category: "Editing",
  },
  {
    id: "add-wait",
    key: "w",
    description: "Add wait",
    action: "addWait",
    category: "Editing",
  },
  {
    id: "add-rotate",
    key: "t",
    description: "Add rotate event",
    action: "addRotate",
    category: "Editing",
  },
  {
    id: "add-event-marker",
    key: "e",
    description: "Add event marker",
    action: "addEventMarker",
    category: "Editing",
  },
  {
    id: "add-control-point",
    key: "a",
    description: "Add control point",
    action: "addControlPoint",
    category: "Editing",
  },
  {
    id: "remove-control-point",
    key: "d",
    description: "Remove control point",
    action: "removeControlPoint",
    category: "Editing",
  },
  {
    id: "duplicate",
    key: "shift+d, cmd+d",
    description: "Duplicate selected item",
    action: "duplicate",
    category: "Editing",
  },
  {
    id: "copy",
    key: "cmd+c, ctrl+c",
    description: "Copy selected item",
    action: "copy",
    category: "Editing",
  },
  {
    id: "cut",
    key: "cmd+x, ctrl+x",
    description: "Cut selected item",
    action: "cut",
    category: "Editing",
  },
  {
    id: "paste",
    key: "cmd+v, ctrl+v",
    description: "Paste item",
    action: "paste",
    category: "Editing",
  },
  {
    id: "remove-selected",
    key: "backspace, delete",
    description: "Remove selected point or wait",
    action: "removeSelected",
    category: "Editing",
  },
  {
    id: "undo",
    key: "cmd+z, ctrl+z",
    description: "Undo",
    action: "undo",
    category: "Editing",
  },
  {
    id: "redo",
    key: "cmd+shift+z, ctrl+shift+z, ctrl+y",
    description: "Redo",
    action: "redo",
    category: "Editing",
  },
  {
    id: "move-point-up",
    key: "i, up",
    description: "Move selected point up",
    action: "movePointUp",
    category: "Editing",
  },
  {
    id: "move-point-down",
    key: "k, down",
    description: "Move selected point down",
    action: "movePointDown",
    category: "Editing",
  },
  {
    id: "move-point-left",
    key: "j, left",
    description: "Move selected point left",
    action: "movePointLeft",
    category: "Editing",
  },
  {
    id: "move-point-right",
    key: "l, right",
    description: "Move selected point right",
    action: "movePointRight",
    category: "Editing",
  },
  {
    id: "increase-val",
    key: "=",
    description: "Increase value (wait/rotate)",
    action: "increaseValue",
    category: "Editing",
  },
  {
    id: "decrease-val",
    key: "-",
    description: "Decrease value (wait/rotate)",
    action: "decreaseValue",
    category: "Editing",
  },
  {
    id: "add-obstacle",
    key: "shift+o",
    description: "Add new obstacle",
    action: "addObstacle",
    category: "Editing",
  },
  {
    id: "focus-name",
    key: "f2, enter",
    description: "Rename selected item",
    action: "focusName",
    category: "Editing",
  },
  {
    id: "deselect-all",
    key: "escape",
    description: "Deselect all",
    action: "deselectAll",
    category: "Navigation",
  },
  {
    id: "toggle-heading-mode",
    key: "shift+h",
    description: "Toggle Heading Mode",
    action: "toggleHeadingMode",
    category: "Editing",
  },
  {
    id: "toggle-reverse",
    key: "shift+r",
    description: "Toggle Reverse",
    action: "toggleReverse",
    category: "Editing",
  },
  {
    id: "toggle-lock",
    key: "shift+l",
    description: "Toggle Locked State",
    action: "toggleLock",
    category: "Editing",
  },

  // Playback
  {
    id: "play-pause",
    key: "space",
    description: "Play / Pause",
    action: "togglePlay",
    category: "Playback",
  },
  {
    id: "increase-speed",
    key: "shift+up",
    description: "Increase playback speed",
    action: "increasePlaybackSpeed",
    category: "Playback",
  },
  {
    id: "decrease-speed",
    key: "shift+down",
    description: "Decrease playback speed",
    action: "decreasePlaybackSpeed",
    category: "Playback",
  },
  {
    id: "reset-playback-speed",
    key: "1",
    description: "Reset playback speed",
    action: "resetPlaybackSpeed",
    category: "Playback",
  },
  {
    id: "step-back",
    key: "shift+left",
    description: "Step animation backward",
    action: "stepBackward",
    category: "Playback",
  },
  {
    id: "step-forward",
    key: "shift+right",
    description: "Step animation forward",
    action: "stepForward",
    category: "Playback",
  },
  {
    id: "reset-animation",
    key: "r",
    description: "Reset animation",
    action: "resetAnimation",
    category: "Playback",
  },

  // View
  {
    id: "toggle-onion",
    key: "o",
    description: "Toggle onion layers",
    action: "toggleOnion",
    category: "View",
  },
  {
    id: "toggle-grid",
    key: "g",
    description: "Toggle grid",
    action: "toggleGrid",
    category: "View",
  },
  {
    id: "cycle-grid-size",
    key: "]",
    description: "Cycle grid spacing",
    action: "cycleGridSize",
    category: "View",
  },
  {
    id: "cycle-grid-size-prev",
    key: "[",
    description: "Cycle grid spacing backward",
    action: "cycleGridSizeReverse",
    category: "View",
  },
  {
    id: "toggle-snap",
    key: "n",
    description: "Toggle snap to grid",
    action: "toggleSnap",
    category: "View",
  },
  {
    id: "toggle-protractor",
    key: "shift+p",
    description: "Toggle protractor",
    action: "toggleProtractor",
    category: "View",
  },
  {
    id: "zoom-in",
    key: "cmd+=, ctrl+=, cmd+shift+=, ctrl+shift+=, cmd+num_add, ctrl+num_add",
    description: "Zoom In",
    action: "zoomIn",
    category: "View",
  },
  {
    id: "zoom-out",
    key: "cmd+-, ctrl+-, cmd+num_subtract, ctrl+num_subtract",
    description: "Zoom Out",
    action: "zoomOut",
    category: "View",
  },
  {
    id: "zoom-reset",
    key: "cmd+0, ctrl+0, cmd+num_0, ctrl+num_0",
    description: "Reset Zoom",
    action: "zoomReset",
    category: "View",
  },
  {
    id: "toggle-collapse-all",
    key: "shift+c",
    description: "Toggle collapse/expand all",
    action: "toggleCollapseAll",
    category: "View",
  },
  {
    id: "toggle-collapse-selected",
    key: "c",
    description: "Toggle collapse selected item",
    action: "toggleCollapseSelected",
    category: "View",
  },
  {
    id: "toggle-sidebar",
    key: "b",
    description: "Toggle sidebar / control tab",
    action: "toggleSidebar",
    category: "View",
  },
  {
    id: "toggle-presentation-mode",
    key: "alt+p",
    description: "Toggle Presentation Mode",
    action: "togglePresentationMode",
    category: "View",
  },
  {
    id: "toggle-velocity-heatmap",
    key: "v",
    description: "Toggle Velocity Heatmap",
    action: "toggleVelocityHeatmap",
    category: "View",
  },

  // Navigation
  {
    id: "select-next-sequence",
    key: "ctrl+down, cmd+down, tab",
    description: "Select Next Sequence Item",
    action: "selectNextSequence",
    category: "Navigation",
  },
  {
    id: "select-prev-sequence",
    key: "ctrl+up, cmd+up, shift+tab",
    description: "Select Previous Sequence Item",
    action: "selectPrevSequence",
    category: "Navigation",
  },
  {
    id: "select-paths-tab",
    key: "alt+1",
    description: "Switch to Paths tab",
    action: "selectTabPaths",
    category: "Navigation",
  },
  {
    id: "select-field-tab",
    key: "alt+2",
    description: "Switch to Field & Tools tab",
    action: "selectTabField",
    category: "Navigation",
  },
  {
    id: "select-table-tab",
    key: "alt+3",
    description: "Switch to Table tab",
    action: "selectTabTable",
    category: "Navigation",
  },
  {
    id: "cycle-tabs-next",
    key: "ctrl+tab",
    description: "Cycle tabs forward",
    action: "cycleTabNext",
    category: "Navigation",
  },
  {
    id: "cycle-tabs-prev",
    key: "ctrl+shift+tab",
    description: "Cycle tabs backward",
    action: "cycleTabPrev",
    category: "Navigation",
  },

  // Tools
  {
    id: "optimize-start",
    key: "ctrl+shift+o",
    description: "Start optimization",
    action: "optimizeStart",
    category: "Optimization",
  },
  {
    id: "optimize-stop",
    key: "ctrl+.",
    description: "Stop optimization",
    action: "optimizeStop",
    category: "Optimization",
  },
  {
    id: "optimize-apply",
    key: "ctrl+enter",
    description: "Apply optimized path",
    action: "optimizeApply",
    category: "Optimization",
  },
  {
    id: "optimize-discard",
    key: "ctrl+backspace",
    description: "Discard optimization",
    action: "optimizeDiscard",
    category: "Optimization",
  },
  {
    id: "optimize-retry",
    key: "ctrl+shift+r",
    description: "Retry optimization",
    action: "optimizeRetry",
    category: "Optimization",
  },
  {
    id: "open-settings",
    key: "cmd+, ctrl+,",
    description: "Open Settings",
    action: "openSettings",
    category: "Settings",
  },
  {
    id: "show-help",
    key: "shift+/",
    description: "Show keyboard shortcuts",
    action: "showHelp",
    category: "Settings",
  },
  {
    id: "toggle-stats",
    key: "s",
    description: "Toggle Path Statistics",
    action: "toggleStats",
    category: "View",
  },
  {
    id: "focus-x",
    key: "x",
    description: "Focus X Input",
    action: "focusX",
    category: "Editing",
  },
  {
    id: "focus-y",
    key: "y",
    description: "Focus Y Input",
    action: "focusY",
    category: "Editing",
  },
  {
    id: "focus-heading",
    key: "h",
    description: "Focus Heading Input",
    action: "focusHeading",
    category: "Editing",
  },
  {
    id: "open-whats-new",
    key: "shift+n",
    description: "Open What's New",
    action: "openWhatsNew",
    category: "Settings",
  },
  {
    id: "toggle-command-palette",
    key: "cmd+p, ctrl+p",
    description: "Toggle Command Palette",
    action: "toggleCommandPalette",
    category: "View",
  },
  {
    id: "open-file",
    key: "cmd+o, ctrl+o",
    description: "Open File",
    action: "openFile",
    category: "File",
  },
  {
    id: "new-file",
    key: "cmd+n, ctrl+n, cmd+r, ctrl+r",
    description: "New Project / Reset Path",
    action: "newProject",
    category: "File",
  },
  {
    id: "toggle-file-manager",
    key: "cmd+shift+m, ctrl+shift+m",
    description: "Toggle File Manager",
    action: "toggleFileManager",
    category: "File",
  },
  {
    id: "export-java",
    key: "cmd+shift+j, ctrl+shift+j",
    description: "Export Java Code",
    action: "exportJava",
    category: "Export",
  },
  {
    id: "export-points",
    key: "cmd+shift+k, ctrl+shift+k",
    description: "Export Points Array",
    action: "exportPoints",
    category: "Export",
  },
  {
    id: "export-sequential",
    key: "cmd+shift+u, ctrl+shift+u",
    description: "Export Sequential Command",
    action: "exportSequential",
    category: "Export",
  },
  {
    id: "export-pp",
    key: "cmd+shift+x, ctrl+shift+x",
    description: "Export .pp (JSON)",
    action: "exportPP",
    category: "Export",
  },
  {
    id: "move-item-up",
    key: "alt+up",
    description: "Move Sequence Item Up",
    action: "moveItemUp",
    category: "Editing",
  },
  {
    id: "move-item-down",
    key: "alt+down",
    description: "Move Sequence Item Down",
    action: "moveItemDown",
    category: "Editing",
  },
  {
    id: "add-path-start",
    key: "alt+s",
    description: "Add Path at Start",
    action: "addPathAtStart",
    category: "Editing",
  },
  {
    id: "add-wait-start",
    key: "shift+w",
    description: "Add Wait at Start",
    action: "addWaitAtStart",
    category: "Editing",
  },
  {
    id: "add-rotate-start",
    key: "alt+t",
    description: "Add Rotate at Start",
    action: "addRotateAtStart",
    category: "Editing",
  },
  {
    id: "validate-path",
    key: "shift+v",
    description: "Validate Path",
    action: "validatePath",
    category: "Tools",
  },
  {
    id: "clear-obstacles",
    key: "ctrl+shift+backspace",
    description: "Clear All Obstacles",
    action: "clearObstacles",
    category: "Editing",
  },
  {
    id: "toggle-diff",
    key: "alt+d",
    description: "Toggle Diff View",
    action: "toggleDiff",
    category: "View",
  },
  {
    id: "toggle-plugin-manager",
    key: "cmd+shift+p, ctrl+shift+p",
    description: "Toggle Plugin Manager",
    action: "togglePluginManager",
    category: "View",
  },
  {
    id: "toggle-ruler",
    key: "alt+m",
    description: "Toggle Ruler",
    action: "toggleRuler",
    category: "View",
  },
  {
    id: "cycle-field-map",
    key: "shift+f",
    description: "Cycle Field Map",
    action: "cycleFieldMap",
    category: "View",
  },
  {
    id: "rotate-field",
    key: "alt+shift+f",
    description: "Rotate Field 90°",
    action: "rotateField",
    category: "View",
  },
  {
    id: "toggle-continuous-validation",
    key: "alt+v",
    description: "Toggle Continuous Validation",
    action: "toggleContinuousValidation",
    category: "Tools",
  },
  {
    id: "toggle-onion-current-path",
    key: "alt+o",
    description: "Toggle Onion Skin (Current Path Only)",
    action: "toggleOnionCurrentPath",
    category: "View",
  },
  {
    id: "edit-item",
    key: "enter",
    description: "Edit selected item properties",
    action: "editItem",
    category: "Editing",
  },
  // Extended Commands
  {
    id: "set-file-manager-directory",
    key: "",
    description: "Set File Manager Directory",
    action: "setFileManagerDirectory",
    category: "File",
  },
  {
    id: "reset-keybinds",
    key: "",
    description: "Reset Keybinds",
    action: "resetKeybinds",
    category: "Settings",
  },
  {
    id: "reset-settings",
    key: "",
    description: "Reset Settings",
    action: "resetSettings",
    category: "Settings",
  },
  {
    id: "cycle-theme",
    key: "shift+t",
    description: "Cycle Light/Dark Mode",
    action: "cycleTheme",
    category: "View",
  },
  {
    id: "show-debug",
    key: "",
    description: "Show/Hide Debug Sequence",
    action: "toggleDebugSequence",
    category: "View",
  },
  {
    id: "toggle-bounds",
    key: "alt+b",
    description: "Toggle Field Boundaries",
    action: "toggleFieldBoundaries",
    category: "View",
  },
  {
    id: "toggle-drag",
    key: "alt+r",
    description: "Toggle Drag Restriction",
    action: "toggleDragRestriction",
    category: "View",
  },
  {
    id: "pan-start",
    key: "home",
    description: "Pan to Start Point",
    action: "panToStart",
    category: "View",
  },
  {
    id: "pan-end",
    key: "end",
    description: "Pan to End Point",
    action: "panToEnd",
    category: "View",
  },
  {
    id: "pan-view-up",
    key: "cmd+shift+up, ctrl+shift+up",
    description: "Pan View Up",
    action: "panViewUp",
    category: "View",
  },
  {
    id: "pan-view-down",
    key: "cmd+shift+down, ctrl+shift+down",
    description: "Pan View Down",
    action: "panViewDown",
    category: "View",
  },
  {
    id: "pan-view-left",
    key: "cmd+shift+left, ctrl+shift+left",
    description: "Pan View Left",
    action: "panViewLeft",
    category: "View",
  },
  {
    id: "pan-view-right",
    key: "cmd+shift+right, ctrl+shift+right",
    description: "Pan View Right",
    action: "panViewRight",
    category: "View",
  },
  {
    id: "select-last",
    key: "shift+end",
    description: "Select Last Point",
    action: "selectLast",
    category: "Editing",
  },
  {
    id: "select-first",
    key: "shift+home",
    description: "Select First Point",
    action: "selectFirst",
    category: "Editing",
  },
  {
    id: "reset-start",
    key: "alt+home",
    description: "Reset Start Point",
    action: "resetStartPoint",
    category: "Editing",
  },
  {
    id: "snap-select",
    key: "shift+s",
    description: "Snap Selection to Grid",
    action: "snapSelection",
    category: "Editing",
  },
  {
    id: "copy-json",
    key: "",
    description: "Copy Path JSON to Clipboard",
    action: "copyPathJson",
    category: "Export",
  },
  {
    id: "theme-light",
    key: "",
    description: "Set Theme: Light",
    action: "setThemeLight",
    category: "Settings",
  },
  {
    id: "theme-dark",
    key: "",
    description: "Set Theme: Dark",
    action: "setThemeDark",
    category: "Settings",
  },
  {
    id: "auto-save-never",
    key: "",
    description: "Autosave: Never",
    action: "setAutoSaveNever",
    category: "Settings",
  },
  {
    id: "auto-save-1m",
    key: "",
    description: "Autosave: 1 Minute",
    action: "setAutoSave1m",
    category: "Settings",
  },
  {
    id: "auto-save-5m",
    key: "",
    description: "Autosave: 5 Minutes",
    action: "setAutoSave5m",
    category: "Settings",
  },
  {
    id: "auto-save-change",
    key: "",
    description: "Autosave: On Change",
    action: "setAutoSaveChange",
    category: "Settings",
  },
  {
    id: "auto-save-close",
    key: "",
    description: "Autosave: On Close",
    action: "setAutoSaveClose",
    category: "Settings",
  },
  {
    id: "docs",
    key: "f1",
    description: "Open Documentation",
    action: "openDocs",
    category: "Help",
  },
  {
    id: "issues",
    key: "",
    description: "Report Issue",
    action: "reportIssue",
    category: "Help",
  },
  {
    id: "start-tutorial",
    key: "",
    description: "Start Interactive Tutorial",
    action: "startTutorial",
    category: "Help",
  },
];
