// Copyright 2026 Matthew Allen. Licensed under the Modified Apache License, Version 2.0.
// What Turtle Tracer may change in a GitHub repository. A team's repository
// holds its whole robot code, so the app only touches its own files: path
// projects, and the code it generates from them.

import { pathInMessage } from "../messagePaths";

export const PROJECT_FILE = /\.(turt|pp)$/i;

export const isProjectFile = (path: string) => PROJECT_FILE.test(path);

/**
 * Generated files the app may write, and how to recognise one it wrote
 * before (so a file a person wrote is never replaced).
 */
const GENERATED: { extension: RegExp; madeByUs: (text: string) => boolean }[] =
  [
    {
      extension: /\.java$/i,
      madeByUs: (text) => text.includes("Turtle Tracer — Auto-Generated"),
    },
    {
      extension: /\.json$/i,
      madeByUs: (text) => text.includes("Created with Turtle Tracer"),
    },
    {
      // The points export: [(x, y), (x, y), ...]
      extension: /\.txt$/i,
      madeByUs: (text) =>
        /^\[(\(-?[\d.]+, -?[\d.]+\)(, )?)*\]$/.test(text.trim()),
    },
  ];

const fileName = (path: string) => path.slice(path.lastIndexOf("/") + 1);

/** Whether a Java file at `path` is where Gradle compiles it. */
export const isCompiledJavaPath = (path: string) =>
  /(^|\/)src\/main\/java\//.test(path);

/** A change Turtle Tracer won't make to a repository. */
export class RepoRuleError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RepoRuleError";
  }
}

/**
 * Throws unless the app may write `content` to `path`. `existing` is the
 * file's current contents, or undefined for a new file.
 */
export function checkWrite(path: string, existing: string | undefined) {
  if (isProjectFile(path)) return;

  const kind = GENERATED.find((g) => g.extension.test(path));
  if (!kind) {
    throw new RepoRuleError(
      `Turtle Tracer only changes path projects and the code it generates, so it won't write ${fileName(path)}.`,
    );
  }
  if (existing !== undefined && !kind.madeByUs(existing)) {
    throw new RepoRuleError(
      `${pathInMessage(path)} wasn't generated by Turtle Tracer, so it won't be replaced. Rename the project or change the Auto Export path.`,
    );
  }
  if (/\.java$/i.test(path) && !isCompiledJavaPath(path)) {
    const folder = path.slice(0, path.lastIndexOf("/"));
    throw new RepoRuleError(
      `${fileName(path)} would go in ${folder ? pathInMessage(folder) : "the top folder"}, where it isn't compiled. Set the Auto Export path to a folder inside TeamCode/src/main/java.`,
    );
  }
}

/** Throws unless the app may delete or rename the file at `path`. */
export function checkRemove(path: string) {
  if (!isProjectFile(path)) {
    throw new RepoRuleError(
      `Turtle Tracer only deletes or renames path projects, not ${fileName(path)}.`,
    );
  }
}

export const FOLDER_RULE =
  "Folders that are on GitHub can't be deleted, renamed or moved here, since they may hold your robot code. Do that in your code editor.";

/**
 * The Java package for a file under src/main/java, from its folder, so
 * generated code always declares the package it's in. Null elsewhere.
 */
export function packageForJavaFile(path: string): string | null {
  const match = /(?:^|\/)src\/main\/java\/(.+)\/[^/]+\.java$/i.exec(path);
  return match ? match[1].replaceAll("/", ".") : null;
}

/**
 * Where generated code for the project at `projectPath` should go: the
 * folder for `packageName` under the same module's src/main/java (TeamCode
 * when the project isn't inside a module).
 */
export function suggestedJavaFolder(
  projectPath: string,
  packageName: string | undefined,
): string {
  const name = packageName?.trim() ?? "";
  const valid = /^[A-Za-z_]\w*(\.[A-Za-z_]\w*)*$/.test(name);
  const packageFolder = (
    valid ? name : "org.firstinspires.ftc.teamcode"
  ).replaceAll(".", "/");
  const sourceRoot = /^(.*?)\/?src\/main\//.exec(projectPath);
  const module = sourceRoot ? sourceRoot[1] : "TeamCode";
  return `${module ? module + "/" : ""}src/main/java/${packageFolder}`;
}
